import os
import re

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

from langchain.llms import Bedrock
from langchain.llms import OpenAI
# from langchain.prompts import PromptTemplate

# Slackbot
SLACK_BOT_TOKEN = os.environ['SLACK_BOT_TOKEN']
SOCKET_MODE_TOKEN = os.environ['SOCKET_MODE_TOKEN']
app = App(token=SLACK_BOT_TOKEN)

# llm
model_id = "anthropic.claude-v2"
llm = Bedrock(model_id=model_id)
#llm = OpenAI()

@app.event("app_mention")
def mention(event, say):
    #メンション部分を除去したメッセージテキスト
    no_mention_text = re.sub(r'^<.*>', '', event['text'])
    thread_ts = event['ts']

    template = f"""あなたは想像力豊かなクリエーターです。 {no_mention_text}"""
    response = f""" {llm(template)}\n\ngenerated by {model_id}"""
    
    say(text=response, thread_ts=thread_ts)

# サーバーの起動
if __name__ == "__main__":
    handler = SocketModeHandler(app, SOCKET_MODE_TOKEN)
    handler.start()

